name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/juanjoboy/random-labyrinth:latest
        
      - name: Build and push dark mode image (dark tag)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/juanjoboy/random-labyrinth:dark
          build-args: |
            DARK_MODE=1